#!/bin/sh

#find images-baseline -name "*.png" | while read line ; do magick $line -transparent green -background black -alpha background -bordercolor none -border 5 -channel A -gaussian-blur 0x1 out/$line; echo $line ; done

find images-baseline -name "*.png" | grep 'fishes/' | grep skeleton | cut -c 16- | while read line ; do magick images-baseline$line -transparent green -background black -alpha background -bordercolor none -border 5 -channel A -gaussian-blur 0x1 images$line; echo images$line ; done

cp images-baseline/fishes/big/right/body_rest_00.png images-baseline/fishes/big/heads/right/head_talking_00.png
cp images-baseline/fishes/big/left/body_rest_00.png images-baseline/fishes/big/heads/left/head_talking_00.png
cp images-baseline/fishes/small/right/body_rest_00.png images-baseline/fishes/small/heads/right/head_talking_00.png
cp images-baseline/fishes/small/left/body_rest_00.png images-baseline/fishes/small/heads/left/head_talking_00.png
find images-baseline -name "*.png" | grep 'fishes/big/right' | grep -vE '_t'   | grep -v skeleton | cut -c 16- | while read line ; do magick images-baseline$line -bordercolor none -border 5 png32:D:/out.png ; magick D:/out.png -channel A -gaussian-blur 0x1 -channel Alpha -separate -fill black -draw "rectangle 49,0 69,39" D:/a.png ; magick D:/out.png D:/a.png -alpha off -compose CopyOpacity -composite images$line; echo images$line ; done
find images-baseline -name "*.png" | grep 'fishes/big/heads/right'             | grep -v skeleton | cut -c 16- | while read line ; do magick images-baseline$line -bordercolor none -border 5 png32:D:/out.png ; magick D:/out.png -channel A -gaussian-blur 0x1 -channel Alpha -separate -fill black -draw "rectangle 0,0  48,39" D:/a.png ; magick D:/out.png D:/a.png -alpha off -compose CopyOpacity -composite images$line; echo images$line ; done
find images-baseline -name "*.png" | grep 'fishes/big/left' | grep -vE '_t'    | grep -v skeleton | cut -c 16- | while read line ; do magick images-baseline$line -bordercolor none -border 5 png32:D:/out.png ; magick D:/out.png -channel A -gaussian-blur 0x1 -channel Alpha -separate -fill black -draw "rectangle 0,0  20,39" D:/a.png ; magick D:/out.png D:/a.png -alpha off -compose CopyOpacity -composite images$line; echo images$line ; done
find images-baseline -name "*.png" | grep 'fishes/big/heads/left'              | grep -v skeleton | cut -c 16- | while read line ; do magick images-baseline$line -bordercolor none -border 5 png32:D:/out.png ; magick D:/out.png -channel A -gaussian-blur 0x1 -channel Alpha -separate -fill black -draw "rectangle 21,0 69,39" D:/a.png ; magick D:/out.png D:/a.png -alpha off -compose CopyOpacity -composite images$line; echo images$line ; done
find images-baseline -name "*.png" | grep 'fishes/small/right' | grep -vE '_t' | grep -v skeleton | cut -c 16- | while read line ; do magick images-baseline$line -bordercolor none -border 5 png32:D:/out.png ; magick D:/out.png -channel A -gaussian-blur 0x1 -channel Alpha -separate -fill black -draw "rectangle 39,0 54,24" D:/a.png ; magick D:/out.png D:/a.png -alpha off -compose CopyOpacity -composite images$line; echo images$line ; done
find images-baseline -name "*.png" | grep 'fishes/small/heads/right'           | grep -v skeleton | cut -c 16- | while read line ; do magick images-baseline$line -bordercolor none -border 5 png32:D:/out.png ; magick D:/out.png -channel A -gaussian-blur 0x1 -channel Alpha -separate -fill black -draw "rectangle 0,0  38,24" D:/a.png ; magick D:/out.png D:/a.png -alpha off -compose CopyOpacity -composite images$line; echo images$line ; done
find images-baseline -name "*.png" | grep 'fishes/small/left' | grep -vE '_t'  | grep -v skeleton | cut -c 16- | while read line ; do magick images-baseline$line -bordercolor none -border 5 png32:D:/out.png ; magick D:/out.png -channel A -gaussian-blur 0x1 -channel Alpha -separate -fill black -draw "rectangle 0,0  15,24" D:/a.png ; magick D:/out.png D:/a.png -alpha off -compose CopyOpacity -composite images$line; echo images$line ; done
find images-baseline -name "*.png" | grep 'fishes/small/heads/left'            | grep -v skeleton | cut -c 16- | while read line ; do magick images-baseline$line -bordercolor none -border 5 png32:D:/out.png ; magick D:/out.png -channel A -gaussian-blur 0x1 -channel Alpha -separate -fill black -draw "rectangle 16,0 54,24" D:/a.png ; magick D:/out.png D:/a.png -alpha off -compose CopyOpacity -composite images$line; echo images$line ; done

#cp /usr/local/share/games/fillets-ng/images/fishes/small/right/body_rest_00.png /usr/local/share/games/fillets-ng/images/fishes/small/left/body_turn_03.png
#cp /usr/local/share/games/fillets-ng/images/fishes/small/left/body_rest_00.png /usr/local/share/games/fillets-ng/images/fishes/small/right/body_turn_03.png

#cp /usr/local/share/games/fillets-ng/images/fishes/small/right/body_turn_00.png /usr/local/share/games/fillets-ng/images/fishes/small/left/body_turn_03.png
#cp /usr/local/share/games/fillets-ng/images/fishes/small/left/body_turn_00.png /usr/local/share/games/fillets-ng/images/fishes/small/right/body_turn_03.png